/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clean.arch.template.core;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
